In [11]:
#W10D2 Esercizi

#ES1
mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]

"""Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione. Come facciamo per accedere ad un elemento in particolare?"""

#Una matrice o tabella.
import numpy as np
maty = np.array(mat) #con la libreria numpy trasformo la lista in ndarray per poterla indicizzare
maty[1:2] #colonna 1, seconda riga

array([[5, 6, 7, 8, 9]])

In [7]:
#ES2
import math

In [9]:
n = 7
math.sin(n)

0.6569865987187891

In [11]:
math.cos(n)

0.7539022543433046

In [13]:
math.factorial(n)

5040

In [15]:
math.pi(n) #pi greco?

TypeError: 'float' object is not callable

In [43]:
#ES3
math.degrees(math.pi) #da pi greco a gradi?

180.0

In [45]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [49]:
#ES4
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] #venduto per mese dell'ultimo anno

#trasformo la lista in array
lsty = np.array(lst)
lsty

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [55]:
#qual è stata la vendita massima mensile? E quella minima? 
vendita_max = np.max(lsty) # vendita massima
vendita_min = np.min(lsty) #vendita minima
print(vendita_max)
print(vendita_min)

8150
1280


In [65]:
#quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? 
filtro = lsty > 5000
filtered = lsty[filtro]
filtered

array([5500, 7200, 6410, 8150, 7100, 5350])

In [69]:
filtered.size

6

In [71]:
#quali sono le vendite minori di 3000 oggetti?
filtro = lsty < 3000
filtered = lsty[filtro]
filtered

array([2000, 1280, 1900, 2500])

In [81]:
#in media quanti oggetti sono stati venduti al mese?
mean = lsty.mean()
print("In media sono stati venduti",mean," oggetti al mese")

In media sono stati venduti 4634.166666666667  oggetti al mese


In [25]:
#ES5
import pandas as pd
fatturati_dict = {1997: 12_000, 
                  1998: 15_000, 
                  1999: 20_000, 
                  2000: 23_000, 
                  2001: 25_000, 
                  2002: 17_000, 
                  2003: 14_000, 
                  2004: 21_000}

fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], 
                             index=range(1997, 2005))

#Possiamo accedere alle stesse informazioni nello stesso modo: 

fatturati_dict[1997] 
fatturati_series[1997]

"""Qual è la differenza tra i due tipi di dato?
La differenza tra un dizionario e una series sta nella dimensionalità della tipologia di dato.
Un dizionario è, infatti, bidimensionale, mentre una series è un array monodimensionale.

#Cosa possiamo fare con la Series che non possiamo fare con il dizionario?
Posso accedere ad un certo dato in una series inserendo direttamente l'indice d'interesse, se in forma int. (?)
"""



"Qual è la differenza tra i due tipi di dato?\nLa differenza tra un dizionario e una series sta nella dimensionalità della tipologia di dato.\nUn dizionario è, infatti, bidimensionale, mentre una series è un array monodimensionale.\n\n#Cosa possiamo fare con la Series che non possiamo fare con il dizionario?\nPosso accedere ad un certo dato in una series inserendo direttamente l'indice d'interesse, se in forma int. (?)\n"

In [29]:
#ES6
import numpy as np
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

#raddoppia gli stipendi sia con un ciclo for, sia con il masking

#metodo 1

for i in stipendi:
    aumento = i*2
    print(aumento)

200
400
600
800
1000
1200
1400
1600
1800
2000


In [31]:
#metodo 2

aumento = stipendi*2
aumento

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [117]:
#ES7
"""Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; 
gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.
"""

#lst=[5,3,20,45,60]
lst = [7,4]
lsty = np.array(lst)
sorted_lsty = np.sort(lsty)[::-1]
print(sorted_lsty)

if len(sorted_lsty)>3:
    print("I tre numeri più grandi sono:", sorted_lsty[0:3])
    
print("Funziona sempre")

len_lsty = len(sorted_lsty[0:3])
print("I", f"{len_lsty}"," numeri più grandi sono:", sorted_lsty[0:3])

[7 4]
Funziona sempre
I 2  numeri più grandi sono: [7 4]


In [129]:
#ES8

"""Scrivere un programma che 
• in input acquisisce una lista di numeri e un numero K 
• in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
• se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato."""

k = 7
inputy = (4,5,6,7,10, k)
inpy = np.array(inputy)
print(np.mean(inputy))

if np.mean(inputy)>= k:
    print(np.mean(inputy))
else: 
    print("I numeri non sono adeguati")


6.5
I numeri non sono adeguati


In [135]:
#ES9

"""Scrivere un programma che, data una lista di numeri, 
come output stamperà lo stesso numero di asterischi su righe diverse, ottenendo una semplice visualizzazione grafica 
Esempio, supponendo di avere il seguente input: numeri = [5, 2, 3, 4] L'output sarà: ***** ** *** ****
"""

lst=[4,5,6,7,1,4]
lsty = np.array(lst)
star = "*"

for i in lst:
    output= star * i
    print(output)


****
*****
******
*******
*
****


In [147]:
#ES10

"""trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla; 
• inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome
"""

lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
lista_95 = []

for i in lista_cf:
    if "95" in i:
        lista_95.append(i)
print(lista_95)

for i in lista_95:
    print("Cognome:", i[0:4])
    print("Nome:", i[4:6])
    


['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
Cognome: ABCD
Nome: EF
Cognome: STUV
Nome: WX
Cognome: DEFG
Nome: HI


In [175]:
#ES11

#stampare a video solo tutti gli studenti che frequentano una prima edizione 

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

for i in range(len(studenti)):
    if edizioni[i]== 1:
        print(studenti[i])


print(len(studenti))
print(range(len(studenti)))

Alex
Faith
8
range(0, 8)


In [177]:
#ES12

#Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro: 

prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] 
new_prezzi= []
#cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; 
#il risultato sarà memorizzato in un'altra lista.

#Marco:
for char in prezzi:
    new_char = ""
    for i in char:
        if i != "€":
            new_char += i
        else:
            new_char += "$"
    new_prezzi.append(new_char)

print(new_prezzi)
        

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [185]:
#ES13

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
#studenty = np.array(studenti)

even = []
odd  = []

for i in range(len(studenti)):
    if i % 2 == 0:
        even.append(studenti[i])
    else:
        odd.append(studenti[i])
print(odd)
print(even)
    

['Bob', 'Dan', 'Faith', 'Henry', 'John']
['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']


In [209]:
#ES14

guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]

"""dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, 
e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti"""

guadagny = np.array(guadagni)
mese = 1
somma = 0

for i in guadagny:
    print("Mese", mese, ":", i)
    if mese == 1:
        print("")
    else:
        media = somma/(mese-1)
        print("La media è:", media)
        if i < media:
            print("La media è maggiore")
        else:
            print("La media è minore")
    mese += 1
    somma += i

Mese 1 : 100

Mese 2 : 90
La media è: 100.0
La media è maggiore
Mese 3 : 70
La media è: 95.0
La media è maggiore
Mese 4 : 40
La media è: 86.66666666666667
La media è maggiore
Mese 5 : 50
La media è: 75.0
La media è maggiore
Mese 6 : 80
La media è: 70.0
La media è minore
Mese 7 : 90
La media è: 71.66666666666667
La media è minore
Mese 8 : 120
La media è: 74.28571428571429
La media è minore
Mese 9 : 80
La media è: 80.0
La media è minore
Mese 10 : 20
La media è: 80.0
La media è maggiore
Mese 11 : 50
La media è: 74.0
La media è maggiore
Mese 12 : 50
La media è: 71.81818181818181
La media è maggiore
